// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "car":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 9 9 9 9 9 9 9 . . . 
. . . . . 9 9 8 8 8 8 8 9 . . . 
. . . . 9 9 8 8 8 8 8 8 9 . . . 
. . . 9 9 8 8 6 6 6 8 8 9 . . . 
6 6 6 6 6 8 7 7 7 7 7 8 6 6 6 6 
6 7 8 8 8 8 8 8 8 8 8 8 8 8 7 6 
6 7 6 6 6 6 7 7 7 7 6 6 6 6 7 6 
6 6 6 f f 6 6 6 6 6 6 f f 6 6 6 
. . . f f . . . . . . f f . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "CYCLE":return img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
.....666................
......6......888........
......6.9998998.........
......6999888889.8......
.....fff98898889fff.....
.....f8f88....88f8f.....
.....fff........fff.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
